CREATE TABLE IF NOT EXISTS jobs (
  id CHAR(36) PRIMARY KEY,
  employer_id CHAR(36) NOT NULL,
  title VARCHAR(255) NOT NULL,
  category_id INT NULL,
  sector VARCHAR(128) NULL,
  description TEXT NULL,
  company_name VARCHAR(255) NULL,
  city VARCHAR(128) NULL,
  job_type VARCHAR(64) NULL,
  experience_level VARCHAR(64) NULL,
  salary_min INT NULL,
  salary_max INT NULL,
  requirements JSON NULL,
  benefits JSON NULL,
  image_url TEXT NULL,
  status ENUM('pending','active','rejected','closed','expired') NOT NULL DEFAULT 'pending',
  featured TINYINT(1) NOT NULL DEFAULT 0,
  expires_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NULL,
  CONSTRAINT fk_jobs_employer FOREIGN KEY (employer_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_jobs_category FOREIGN KEY (category_id) REFERENCES job_categories(id) ON DELETE SET NULL,
  INDEX idx_jobs_status (status),
  INDEX idx_jobs_employer (employer_id),
  INDEX idx_jobs_featured (featured),
  INDEX idx_jobs_created (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
