CREATE TABLE IF NOT EXISTS uploaded_files (
  id VARCHAR(80) PRIMARY KEY,
  mime VARCHAR(128) NOT NULL DEFAULT 'application/octet-stream',
  data LONGBLOB NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
